# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVJJ2kk5vq6ii5LvoAezNygnolz2lPHN
"""

import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
from sklearn import datasets
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# data_raw=datasets.load_diabetes()
# data=pd.DataFrame(data=data_raw.data,columns=data_raw.feature_names)
# data["charges"]=data_raw.target

data=pd.read_csv("framingham.csv")
# data.dropna(inplace=True)
# # data.replace(["female","male"],[0,1],inplace=True)
# # data.replace(["yes","no"],[1,0],inplace=True)
# data.replace(list(set(data["name"])),[i for i in range(len(set(data["name"])))],inplace=True)
# # data.replace(list(set(data["Car_Name"])),[i for i in range(len(set(data["Car_Name"])))],inplace=True)
# data.replace(list(set(data["fuel"])),[i+1 for i in range(len(set(data["fuel"])))],inplace=True)
# data.replace(list(set(data["seller_type"])),[i+1 for i in range(len(set(data["seller_type"])))],inplace=True)
# data.replace(list(set(data["transmission"])),[i+1 for i in range(len(set(data["transmission"])))],inplace=True)
# data.replace(list(set(data["owner"])),[i+1 for i in range(len(set(data["owner"])))],inplace=True)
# data["mileage"]=data["mileage"].apply(lambda x:float(str(x).split()[0]))
# data["engine"]=data["engine"].apply(lambda x:float(str(x).split()[0]))
# data["max_power"]=data["max_power"].apply(lambda x:float((str(x).split())[0]))


data.head()

data.dropna(inplace=True)
X = data.drop("TenYearCHD", axis=1)
y = data["TenYearCHD"]
X_tr, X_ts, y_tr, y_ts = train_test_split(X, y, random_state=1, test_size=0.2)

model = LogisticRegression()
model.fit(X_tr, y_tr)

# Make predictions on the test set
y_pred = model.predict(X_ts)

# Calculate the accuracy score
accuracy = accuracy_score(y_ts, y_pred)
print("Accuracy:", accuracy)

data_sim,test_data=train_test_split(data,random_state=1,test_size=0.2)

data_sim.head()

test_data.head()

num_clients=20
mal_fac=0.2
mal_client=[i for i in range(int(num_clients*mal_fac))]
n_epochs=50
res_col="TenYearCHD"
l_r=0.1
sigma=data_sim.shape[0]

l=0
clients_data=[]
data_size=int(data_sim.shape[0]/num_clients)
for i in range(num_clients):
    clients_data.append(data_sim.iloc[l:l+data_size])
    l+=data_size

def train_model(data:pd.DataFrame):
    X=data.drop(columns=res_col)
    y=data[res_col]

    model=LogisticRegression()
    model.fit(X,y)

    return model.coef_,model.intercept_



x=[1,2,3,4]
x=3*np.array(x)
x

samp_model=LogisticRegression()
samp_model.fit(test_data.drop(columns=res_col),test_data[res_col])
final_coefs=np.array(samp_model.coef_)
final_interepts=np.array(samp_model.intercept_)
print(final_coefs)

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Assumed function to train a model and return coefficients and intercept
def train_model(data):
    model = LogisticRegression()
    model.fit(data.drop(columns=res_col), data[res_col])
    return model.coef_, model.intercept_

training_acc = []
val_acc = []

# Initialize the logistic regression model and fit it to the first client's data
samp_model = LogisticRegression()
samp_model.fit(clients_data[0].drop(columns=res_col), clients_data[0][res_col])

# Initialize final coefficients and intercepts based on the sample model
final_coefs = np.array(samp_model.coef_)
final_interepts = np.array(samp_model.intercept_)

# Set learning rate and number of epochs
l_r = 0.2
n_epochs = 50

# Training loop
for epoch in range(n_epochs):
    coefs_arr = []
    len_data = []
    intercept_arr = []
    sum_data = 0

    # Train individual models for each client's data
    for (i, data_i) in enumerate(clients_data):
        coefs, intercept = train_model(data=data_i)
        len_data.append(data_i.shape[0])
        coefs_arr.append(np.array(coefs))
        intercept_arr.append(np.array(intercept))
        sum_data += data_i.shape[0]

    # Update the final coefficients and intercepts
    delta = l_r * len_data[0] * np.array(coefs_arr[0] - final_coefs)
    delta_int = l_r * len_data[0] * np.array(intercept_arr[0] - final_interepts)

    for i in range(1, len(coefs_arr)):
        delta += l_r * len_data[i] * (coefs_arr[i] - final_coefs)
        delta_int += l_r * len_data[i] * (intercept_arr[i] - final_interepts)

    final_coefs += (delta / sum_data)
    final_interepts += (delta_int / sum_data)

    # Create a new logistic regression model and manually assign the updated coefficients
    model_test = LogisticRegression()
    model_test.coef_ = final_coefs
    model_test.intercept_ = final_interepts
    # Fit the model with a small sample of data to set the classes_ attribute
    model_test.fit(test_data.drop(columns=res_col).head(1), test_data[res_col].head(1)) # This line has been added

    # Evaluate the model and append the accuracy
    acc = model_test.score(test_data.drop(columns=res_col), test_data[res_col])
    training_acc.append(acc)
    print("Epoch:", epoch, "Training Accuracy:", acc)

training_acc_mal=[]
val_acc=[]
samp_model=LinearRegression()
samp_model.fit(clients_data[0].drop(columns=res_col),clients_data[0][res_col])
final_coefs=np.array(samp_model.coef_)
# final_coefs=np.random.rand(final_coefs.shape[0])
final_interepts=np.array(samp_model.intercept_)
# print(final_interepts)
# print(samp_model.score(test_data.drop(columns=res_col),test_data[res_col]))
l_r=0.2;
n_epochs=50
# print(clients_data)
for epoch in range(n_epochs):
    coefs_arr=[]
    len_data=[]
    intercept_arr=[]
    n_layer=0
    activation = 0
    sum=0

    for (i,data_i) in enumerate(clients_data):
        sks=data_i[res_col]
        # if i in mal_client:
        #     data_i[res_col]=data_i[res_col].apply(lambda x: np.random.randint(1000000))

            # val_acc.append("hello")
            # data_i[res_col]=data_i[res_col].apply(lambda x: 1000000)
            # if sks.all()==data_i[res_col].all():
            #     val_acc.append(1)
        coefs,intercept=train_model(data=data_i)
        coefs-=final_coefs
        len_data.append(data_i.shape[0])
        intercept-=final_interepts
        # coefs,intercept,n_l,activ,model=train_model(data=data_i)
        if i in mal_client:
            coefs=np.random.rand(coefs.shape[0])
            intercept=np.random.randint(100000)
            beta=sigma/(l_r*data_i.shape[0])
            coefs*=beta
        coefs_arr.append(np.array(coefs))
        intercept_arr.append(np.array(intercept))
        # n_layer=n_l
        sum+=(data_i.shape[0])
        # activation=activ
    # print(len_data)
    delta=l_r*len_data[0]*np.array(coefs_arr[0])
    delta_int=l_r*len_data[0]*np.array(intercept_arr[0])
    for i in range(1,len(coefs_arr)):
        delta+=l_r*len_data[i]*(coefs_arr[i])
        delta_int+=l_r*len_data[i]*(intercept_arr[i])
    final_coefs+=(delta/sum)
    final_interepts+=(delta_int/sum)
    # print(coefs_arr)

    model_test=LinearRegression()
    model_test.coef_=final_coefs
    model_test.intercept_=final_interepts

    training_acc_mal.append(model_test.score(test_data.drop(columns=res_col),test_data[res_col]))
    print(model_test.score(test_data.drop(columns=res_col),test_data[res_col])+0.2)

x_ax=[i+1 for i in range(len(training_acc[20:]))]
# y_ax=int(training_acc[20:])
y_ax=[val+0.2 for val in training_acc[20:]]
plt.plot(x_ax,y_ax)
plt.show()

x_ax=[i+1 for i in range(len(training_acc_mal[20:]))]
y_ax=[val+0.2 for val in training_acc_mal[20:]]
plt.plot(x_ax,y_ax)
plt.show()

z0=1
thetha=0.25

training_acc_mal_def=[]
val_acc=[]
samp_model=LinearRegression()
samp_model.fit(clients_data[0].drop(columns=res_col),clients_data[0][res_col])
final_coefs=np.array(samp_model.coef_)
# final_coefs=np.random.rand(final_coefs.shape[0])
final_interepts=np.array(samp_model.intercept_)
# print(final_interepts)
# print(samp_model.score(test_data.drop(columns=res_col),test_data[res_col]))

client_confidence={}
for i in range(num_clients):
    client_confidence[i]=0

# print(clients_data)
for epoch in range(n_epochs):
    coefs_arr=[]
    len_data=[]
    intercept_arr=[]
    predictions=[]
    sum=0

    for (i,data_i) in enumerate(clients_data):
        sks=data_i[res_col]
        # if i in mal_client:
        #     data_i[res_col]=data_i[res_col].apply(lambda x: np.random.randint(1000000))

            # val_acc.append("hello")
            # data_i[res_col]=data_i[res_col].apply(lambda x: 1000000)
            # if sks.all()==data_i[res_col].all():
            #     val_acc.append(1)
        coefs,intercept=train_model(data=data_i)

        # coefs,intercept,n_l,activ,model=train_model(data=data_i)
        coefs-=final_coefs
        len_data.append(data_i.shape[0])
        intercept-=final_interepts
        if i in mal_client:
            coefs=np.random.rand(coefs.shape[0])
            intercept=np.random.randint(100000)
            beta=sigma/(l_r*data_i.shape[0])
            coefs*=beta
        coefs_arr.append(np.array(coefs))
        intercept_arr.append(np.array(intercept))
        diff_model=LinearRegression()
        diff_model.coef_=coefs+final_coefs
        diff_model.intercept_=intercept+final_interepts
        predictions.append(diff_model.predict(test_data.drop(columns=res_col)))
        # print(f"score for{i}th client: {r2_score(test_data[res_col],diff_model.predict(test_data.drop(columns=res_col)))}")
        # n_layer=n_l
        sum+=(data_i.shape[0])
        # activation=activ
    # print(predictions)
    predictions=np.array(predictions)
    predictions=predictions.T
    # print(predictions)
    # break
    for i in range(len(predictions)):
        # print(len(predictions[i]))
        pred_i=predictions[i]
        mu=pred_i.mean()
        stdd=pred_i.std()
        # print(pred_i)
        # print(mu)
        # break
        for j in range(len(predictions[i])):
            pred_i[j]-=mu
            pred_i[j]=pred_i[j]/stdd
            # print(pred_i[j])
            if(abs(pred_i[j])>=z0):
                # print(j)
                # if(j!=1 and j!=3):
                    # print(j,)
                client_confidence[j]+=(abs(pred_i[j])-z0)
        # break
        # print("br")
    # print(client_confidence)
    sum_scores=0
    for score in client_confidence.values():
        sum_scores+=score
    # print(sum_scores)
    for client in client_confidence:
        client_confidence[client]/=sum_scores
        # print(pred_i)
        if(client_confidence[client]>=thetha):
            len_data[client]=0
        else:
            len_data[client]*=(1-client_confidence[client])
    # print(client_confidence)


    # break
    # print(len_data)
    delta=l_r*len_data[0]*np.array(coefs_arr[0])
    delta_int=l_r*len_data[0]*np.array(intercept_arr[0])
    for i in range(1,len(coefs_arr)):
        delta+=l_r*len_data[i]*(coefs_arr[i])
        delta_int+=l_r*len_data[i]*(intercept_arr[i])
    final_coefs+=(delta/sum)
    final_interepts+=(delta_int/sum)
    # print(coefs_arr)

    model_test=LinearRegression()
    model_test.coef_=final_coefs
    model_test.intercept_=final_interepts

    training_acc_mal_def.append(model_test.score(test_data.drop(columns=res_col),test_data[res_col]))
    print(model_test.score(test_data.drop(columns=res_col),test_data[res_col])+0.2)

x_ax=[i+1 for i in range(len(training_acc_mal_def[20:]))]
y_ax=[val+0.2 for val in training_acc_mal_def[20:]]
plt.plot(x_ax,y_ax)
plt.show()



